package com.smarttoolfactory.tutorial6_4_sucomponentfactory_multipleactivitiesandfragments.model

import com.smarttoolfactory.tutorial6_4_sucomponentfactory_multipleactivitiesandfragments.di.scope.FragmentScope
import javax.inject.Inject

@FragmentScope
class FragmentObject @Inject constructor()